# Generated by Django 5.1.2 on 2024-10-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images_api', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['author'], name='idx_author'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['width'], name='idx_width'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['height'], name='idx_height'),
        ),
    ]
